weareprestatech/hotpdf

README.md, hotpdf/hotpdf.py
- Updated README to contain more information
- Made internal function (extract_full_text_span) private
=> Update README and make internal function private

.github/workflows/pull-requests-ci.yml, hotpdf/memory_map.py
- Reduce the complexity of the load_memory_map function
- Reduce tolerance of flake8 max_complexity to 10
Issue: https://github.com/weareprestatech/hotpdf/issues/6
=> Reduce complexity of load_memory_map function and flake8 max_complexity

README.md, docs/source/conf.py, docs/source/index.rst
- Cleanup documentation
- Update links to point to correct docs
=> Cleanup docs and update links

README.md, docs/source/generated/hotpdf.helpers.nanoid.rst, docs/source/generated/hotpdf.hotpdf.HotPdf.rst, docs/source/generated/hotpdf.memory_map.MemoryMap.rst, docs/source/generated/hotpdf.processor.rst, docs/source/generated/hotpdf.span_map.SpanMap.rst, docs/source/generated/hotpdf.sparse_matrix.SparseMatrix.rst, docs/source/generated/hotpdf.trie.Trie.rst, docs/source/generated/hotpdf.trie.TrieNode.rst, docs/source/generated/hotpdf.utils.rst, docs/source/index.rst
- Updated docs to include pip install
=> Update docs with pip information

docs/source/api.rst, docs/source/generated/hotpdf.data.classes.ElementDimension.rst, docs/source/generated/hotpdf.data.classes.HotCharacter.rst, docs/source/generated/hotpdf.data.classes.Span.rst, docs/source/usage.rst
- Moved a few things around in the documentation to make the hierarchy proper
- Added more things under API
=> Fix documentation layout

hotpdf/data/classes.py
- Added a space before Attributes to fix some rendering issues with Sphinx
@callegarimattia pls approve it's the last one for today (hopefully) 😄
=> Fix formatting issues in attributes

tests/test_benchmark.py
- Added speed benchmark tests
- Added memory benchmark tests
- Removed unused file
=> Add benchmark tests

tests/test_benchmark.py
- Update benchmark values to fix tests.
=> Update benchmark values to fix tests

.github/workflows/test.yml, README.md, pyproject.toml
First part done!
We only need to set up the coverall token in the repo secrets
Closes: #43
=> build: add coverage badge

tests/resources/xml/hotpdf_bank_negative_coords.xml, tests/resources/xml/hotpdf_bank_normal_coords.xml, tests/test_functions.py
- Added test for handling negative coordinates
with this - finally 100% coverage locally
=> Add test to handle negative coordinates

pyproject.toml
@callegarimattia we would need to automate this next. We could take the tag from the release
=> Update version to 0.3.2

.github/workflows/build-badge.yml, .github/workflows/release-badge.yml, .github/workflows/test.yml, pyproject.toml
- Added matrix testing of multiple python versions (3.9, 3.10, 3.11)
- Added legacy fallback for setuptools
=> Support python 3.9, 3.10

.github/workflows/test.yml, hotpdf/memory_map.py, hotpdf/utils.py
- Removed repeated checks for indexing
- Removed unnecessary enumerates
- Removed deepcopy, instead used a simple slice
- Removed unnecessary type casts
- Continue before doing some extra steps
=> Small optimisations - rewrote some lines

hotpdf/data/classes.py, hotpdf/hotpdf.py, hotpdf/utils.py, tests/test_functions.py, tests/test_load.py
Add util function to convert to string
=> feat: to_text

hotpdf/hotpdf.py, tests/test_load.py
- Removed file double-loading exception
=> Remove double loading exception

hotpdf/hotpdf.py, hotpdf/memory_map.py, tests/test_functions.py, tests/test_load.py
- Removed duplicate functions. Functions were duplicated by the implementation of: https://github.com/weareprestatech/hotpdf/pull/58
- Renamed extract_page to extract_page_text
- Made page for extract_page_text to be required.
- Added tests for new functions
=> Remove duplicate functions and update function signature

.github/workflows/test.yml, hotpdf/data/classes.py, hotpdf/hotpdf.py, hotpdf/span_map.py, hotpdf/utils.py, pyproject.toml, tests/test_functions.py
Some memory savings
jk: memory is same basically
Link: #15
=> feat: tried to reduce memory but only cleaned up the code 😢 

docs/source/generated/hotpdf.data.classes.Span.rst, docs/source/generated/hotpdf.hotpdf.HotPdf.rst, docs/source/generated/hotpdf.memory_map.MemoryMap.rst, docs/source/generated/hotpdf.utils.rst, docs/source/guide.rst, docs/source/index.rst, docs/source/usage.rst, hotpdf/hotpdf.py, tests/test_load.py
- Added User Guide for better explanation of functions.
Issue: https://github.com/weareprestatech/hotpdf/issues/32
=> Add User Guide documentation

.pre-commit-config.yaml, hotpdf/data/classes.py, hotpdf/helpers/nanoid.py, hotpdf/hotpdf.py, hotpdf/memory_map.py, hotpdf/processor.py, hotpdf/span_map.py, hotpdf/sparse_matrix.py, hotpdf/trie.py, hotpdf/utils.py, pyproject.toml, tests/test_functions.py, tests/test_load.py
Made extract_spans return the Span class
=> feat: change return value of extract_spans

README.md, docs/source/conf.py, docs/source/guide.rst, docs/source/index.rst, docs/source/usage.rst
- Edited docs to reflect updated extract_spans function
- Some small doc fixes
- Added doc contrib section in Readme
=> Update docs for new version

README.md
Somehow in my last PR, I forgot to update the README.md file with the Documentation guide. When in fact, I wrote the .md first and then converted it to .rst file. 
Anyway, here's it again!
=> Update readme with documentation guide

hotpdf/hotpdf.py, hotpdf/memory_map.py, hotpdf/span_map.py
- Use yield in the SparseMatrix items function.
- Removed todo comment
- Removed LRU cache
=> Use yield in SparseMatrix items function + remove lru_cache

hotpdf/span_map.py, tests/test_load.py
- Added test to test condition when Span has characters = None
- Remove else condition from span insert method
=> Add test for no characters in Span + remove else in Span insert

README.md, docs/source/generated/hotpdf.processor.rst, docs/source/guide.rst, docs/source/usage.rst
Added docs for https://github.com/weareprestatech/hotpdf/pull/72
=> Add docs for PR #72

.github/workflows/test.yml, hotpdf/processor.py, pyproject.toml, tests/conftest.py, tests/resources/invalid_file.txt, tests/test_benchmark.py, tests/test_functions.py, tests/test_load.py, tests/test_slow_benchmark.py
- Fixed bug on unix, where the wrong Exception was raised
- Added a benchmark with a big file for testing (not included in CI for now)
=> test: add file invalid test, fix nt wrong exception raised

hotpdf/processor.py
- I read on stack overflow and github that doing these somewhat affects performance. So I implemented these. Nothing breaking, so won't hurt :)
=> feat(?): Implement suggestions from the internet for optimisations

.gitignore, demo.py, main.py
=> chore: Cleanup main.py and add demo.py

pyproject.toml
- Update pdfminer version to >= current to support custom forks
=> set pdfminer version >=current to support custom forks

README.md, docs/source/index.rst
Updated readme to add installation for fork of pdfminer.six
=> Update readme to add pdfminer.six fork installation
